### PR TITLE
Add @Documented to @Api.

### PR DESCRIPTION
**Pull request by MaloJaffre**
This is only for documentation purposes.

### CODE REVIEW

**Comment by Cervator** [comment]
Did you mean to create this PR for MovingBlocks or is it just an internal one for yourself?

**Comment by MaloJaffre** [comment]
No, this is for MovingBlocks.

**Comment by Cervator** [comment]
Wrong place then :D You made this PR aimed at your own fork :-)

Happens sometimes by accident and some do it on purpose to track their own work.

**Comment by MaloJaffre** [comment]
Thanks, I will recreate the PR in the right place.

**Pull request closed without merging**
